### PR TITLE
Avoid using celery 5.0

### LINKED ISSUE #79: Compatibility with Django v5.0
Hi,

Has anybody been able to get django-celery-email working with celery 5? I have tried to get it running but get an error and not sure of it should work out of the box or there is some compatibility issue.

Thanks

### PR DESCRIPTION
**Pull request by palvarez89**
Fixes #79

### CODE REVIEW

**Comment by tartieret** [comment]
The package works perfectly with Celery > 5.0

**Comment by palvarez89** [comment]
Ah, thanks for doing the digging! Closing this

**Comment by tartieret** [comment]
@palvarez89 do you maintain this project ? I am happy to provide some help as I am considering using this package for my company

**Comment by palvarez89** [comment]
> @palvarez89 do you maintain this project ? I am happy to provide some help as I am considering using this package for my company

Nope, just another user of this project. Was actually wondering if this project is maintained.

**Comment by tartieret** [comment]
@pmclanahan would you like some help?

**Comment by pmclanahan** [comment]
Hi. Any help is definitely appreciated.

**Comment by tartieret** [comment]
@pmclanahan what do you suggest? It seems that checking the compatibility with Celery 5 and updating the docs / requirements to include Celery 5 would be the main thing to do ? I am happy to take this on, should I submit a pull request for it ?

**Comment by pmac** [comment]
That would be very helpful indeed! Any help is much appreciated. I'll take a look as they come in.

**Pull request closed without merging**
