### PR TITLE
Support Django 1.6. Add TravisCI. Chunk messages.

### PR DESCRIPTION
**Pull request by pmclanahan**
Thanks to @jonashaag at Github for the contribution.

### CODE REVIEW

**Comment by pmclanahan** [comment]
This replaces #3. Unfortunately I was a horrible maintainer and Jonas gave up. Hopefully we can get his excellent work in anyway, if terribly late.

**Comment by jonashaag** [comment]
I deleted my fork because there was some more development happening over at https://github.com/DigiACTive/django-celery-email (which includes all of my changes).

My suggestion is to undo the merge you just did and/or merge that repository. It contains the JSON support patch.

**Comment by pmclanahan** [comment]
Nice! Thanks @jonashaag.

**Comment by pmclanahan** [comment]
@jonashaag do you think DigiACTive is a better home for this project? I've clearly failed to keep up with this well enough, which is mostly due to me no longer using this regularly. I'm happy to take on maintainers or move it to a better home. I'm just happy to learn it's still useful to people :)

**Comment by daxtens** [comment]
Hi, I was one of the developers at DigiACTive. The company is no more, so it's probably not the best home, sorry!

**Comment by pmclanahan** [comment]
No problem. I'll pull in the changes and pay better attention.  Thanks for
the help all!

**Comment by pmclanahan** [comment]
Pulled these changes from @DigiACTive.

**Pull request closed without merging**
